// lib/fab-constants/sets-data.generated.ts
//
// AUTO-GENERATED from the `sets` table by scripts/generate-set-constants.ts
// — DO NOT EDIT BY HAND. The database is the source of truth: update the row
// (or add one for a new set), then regenerate with
//
//   npx tsx --env-file=.env.local scripts/generate-set-constants.ts
//
// Ordered by release_order (global chronological release ordering).

import type { SetMetadata } from './sets';

export const SET_MAP = {
  "ira": "Welcome Deck: Ira",
  "wtr": "Welcome to Rathe",
  "bvo": "Hero Deck: Bravo",
  "ksu": "Hero Deck: Katsu",
  "rnr": "Hero Deck: Rhinar",
  "tea": "Hero Deck: Dorinthea",
  "fab": "Flesh and Blood: Promo Cards",
  "her": "Hero Card Promos",
  "jdg": "Judge Promos",
  "lgs": "Local Game Store Promos",
  "lss": "LSS Promos",
  "tnp": "Tournament Prize Cards",
  "win": "Worlds / Pro Tour Prize Cards",
  "xxx": "OP Event Tokens",
  "arc": "Arcane Rising",
  "cru": "Crucible of War",
  "mon": "Monarch",
  "bol": "Blitz Deck: Monarch - Boltyn",
  "chn": "Blitz Deck: Monarch - Chane",
  "lev": "Blitz Deck: Monarch - Levia",
  "psm": "Blitz Deck: Monarch - Prism",
  "ele": "Tales of Aria",
  "bri": "Blitz Deck: Tales of Aria - Briar",
  "lxi": "Blitz Deck: Tales of Aria - Lexi",
  "old": "Blitz Deck: Tales of Aria - Oldhim",
  "evr": "Everfest",
  "1hp": "History Pack Vol.1",
  "dvr": "Classic Battles: Rhinar vs Dorinthea",
  "rvd": "Classic Battles: Rhinar vs Dorinthea - Rhinar",
  "upr": "Uprising",
  "dro": "Blitz Deck: Uprising - Dromai",
  "fai": "Blitz Deck: Uprising - Fai",
  "dyn": "Dynasty",
  "1hb": "Historic Pack 1 Blitz Deck: Bravo",
  "1hd": "Historic Pack 1 Blitz Deck: Dash",
  "1hk": "Historic Pack 1 Blitz Deck: Kano",
  "1hr": "Historic Pack 1 Blitz Deck: Rhinar",
  "1ht": "Historic Pack 1 Blitz Deck: Dorinthea",
  "1hv": "Historic Pack 1 Blitz Deck: Viserai",
  "out": "Outsiders",
  "ara": "Blitz Deck: Outsiders - Arakni",
  "azl": "Blitz Deck: Outsiders - Azalea",
  "ben": "Blitz Deck: Outsiders - Benji",
  "kat": "Blitz Deck: Outsiders - Katsu",
  "rip": "Blitz Deck: Outsiders - Riptide",
  "uzu": "Blitz Deck: Outsiders - Uzuri",
  "dtd": "Dusk till Dawn",
  "tcc": "Round the Table: TCCxLSS",
  "evo": "Bright Lights",
  "gem": "GEM Pack 2",
  "oxo": "Slingshot Underground Promos",
  "hvy": "Heavy Hitters",
  "bet": "Blitz Deck: Heavy Hitters - Betsy",
  "ksi": "Blitz Deck: Heavy Hitters - Kassai",
  "kyo": "Blitz Deck: Heavy Hitters - Kayo",
  "ola": "Blitz Deck: Heavy Hitters - Olympia",
  "rhi": "Blitz Deck: Heavy Hitters - Rhinar",
  "vic": "Blitz Deck: Heavy Hitters - Victor",
  "ako": "Armory Deck: Kayo",
  "mst": "Part the Mistveil",
  "eng": "Blitz Deck: Part the Mistveil - Enigma",
  "nuu": "Blitz Deck: Part the Mistveil - Nuu",
  "zen": "Blitz Deck: Part the Mistveil - Zen",
  "asb": "Armory Deck: Boltyn",
  "aaz": "Armory Deck: Azalea",
  "aur": "1st Strike",
  "ter": "First Strike: Terra",
  "ros": "Rosetta",
  "aua": "Blitz Deck: Rosetta - Aurora",
  "flr": "Blitz Deck: Rosetta - Florian",
  "osc": "Blitz Deck: Rosetta - Oscilio",
  "ver": "Blitz Deck: Rosetta - Verdance",
  "aio": "Armory Deck: Dash",
  "ajv": "Armory Deck: Jarl Vetreidi",
  "hnt": "The Hunted",
  "ark": "Blitz Deck: The Hunted - Arakni",
  "cin": "Blitz Deck: The Hunted - Cindra",
  "fng": "Blitz Deck: The Hunted - Fang",
  "wod": "Blitz Deck: The Hunted - Arakni, Web of Deceit",
  "ast": "Armory Deck: Aurora",
  "amx": "Armory Deck: Maxx Nitro",
  "agb": "Armory Deck: Gravy Bones",
  "sea": "High Seas",
  "asr": "Armory Deck: Ira",
  "apr": "Armory Deck Legends: Prism",
  "avs": "Armory Deck Legends: Viserai",
  "mpg": "Mastery Pack Guardian",
  "bdd": "Bravo Demo Deck",
  "smp": "Smash Palace",
  "aps": "Armory Deck: Pleiades",
  "sup": "Super Slam",
  "arr": "Armory Deck: Rhinar",
  "aac": "Armory Deck: Arakni",
  "anq": "Antiquity Pack",
  "pen": "Compendium of Rathe",
  "sar": "Silver Age Deck: Arakni",
  "saz": "Silver Age Deck: Azalea",
  "sbr": "Silver Age Deck: Bravo",
  "sda": "Silver Age Deck: Dash",
  "sdo": "Silver Age Deck: Dorinthea",
  "sen": "Silver Age Deck: Enigma",
  "sfa": "Silver Age Deck: Fai",
  "siy": "Silver Age Deck: Iyslander",
  "ska": "Silver Age Deck: Kayo",
  "svi": "Silver Age Deck: Viserai",
  "aha": "Armory Deck Origins: Hala",
  "azs": "Armory Deck: Zyggy",
  "omn": "Omens of the Third Age",
  "iar": "Íarathael Preview Cards",
  "mpw": "Mastery Pack Warrior",
  "ddd": "Dorinthea Demo Deck",
  "aol": "Armory Deck: Olympia",
} as const;

export const SET_METADATA: Record<string, SetMetadata> = {
  "ira": { code: "IRA", name: "Welcome Deck: Ira", releaseDate: "2019-08-31", hasFirstEdition: false, category: "excluded", tier: 3, displayOrder: 410 },
  "wtr": { code: "WTR", name: "Welcome to Rathe", releaseDate: "2019-10-11", hasFirstEdition: true, category: "standard", tier: 1, displayOrder: 10 },
  "bvo": { code: "BVO", name: "Hero Deck: Bravo", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 420 },
  "ksu": { code: "KSU", name: "Hero Deck: Katsu", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 430 },
  "rnr": { code: "RNR", name: "Hero Deck: Rhinar", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 440 },
  "tea": { code: "TEA", name: "Hero Deck: Dorinthea", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 450 },
  "fab": { code: "FAB", name: "Flesh and Blood: Promo Cards", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 270 },
  "her": { code: "HER", name: "Hero Card Promos", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 280 },
  "jdg": { code: "JDG", name: "Judge Promos", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 290 },
  "lgs": { code: "LGS", name: "Local Game Store Promos", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 300 },
  "lss": { code: "LSS", name: "LSS Promos", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 310 },
  "tnp": { code: "TNP", name: "Tournament Prize Cards", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 320 },
  "win": { code: "WIN", name: "Worlds / Pro Tour Prize Cards", releaseDate: "2019-10-11", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 330 },
  "xxx": { code: "XXX", name: "OP Event Tokens", releaseDate: "2019-10-11", hasFirstEdition: false, category: "excluded", tier: 5, displayOrder: 340 },
  "arc": { code: "ARC", name: "Arcane Rising", releaseDate: "2020-03-27", hasFirstEdition: true, category: "standard", tier: 1, displayOrder: 20 },
  "cru": { code: "CRU", name: "Crucible of War", releaseDate: "2020-08-28", hasFirstEdition: true, category: "standard", tier: 1, displayOrder: 30 },
  "mon": { code: "MON", name: "Monarch", releaseDate: "2021-05-07", hasFirstEdition: true, category: "standard", tier: 1, displayOrder: 40 },
  "bol": { code: "BOL", name: "Blitz Deck: Monarch - Boltyn", releaseDate: "2021-05-07", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 460 },
  "chn": { code: "CHN", name: "Blitz Deck: Monarch - Chane", releaseDate: "2021-05-07", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 470 },
  "lev": { code: "LEV", name: "Blitz Deck: Monarch - Levia", releaseDate: "2021-05-07", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 480 },
  "psm": { code: "PSM", name: "Blitz Deck: Monarch - Prism", releaseDate: "2021-05-07", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 490 },
  "ele": { code: "ELE", name: "Tales of Aria", releaseDate: "2021-09-24", hasFirstEdition: true, category: "standard", tier: 1, displayOrder: 50 },
  "bri": { code: "BRI", name: "Blitz Deck: Tales of Aria - Briar", releaseDate: "2021-11-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 500 },
  "lxi": { code: "LXI", name: "Blitz Deck: Tales of Aria - Lexi", releaseDate: "2021-11-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 510 },
  "old": { code: "OLD", name: "Blitz Deck: Tales of Aria - Oldhim", releaseDate: "2021-11-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 520 },
  "evr": { code: "EVR", name: "Everfest", releaseDate: "2022-02-04", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 60 },
  "1hp": { code: "1HP", name: "History Pack Vol.1", releaseDate: "2022-05-06", hasFirstEdition: false, category: "standard", tier: 2, displayOrder: 200 },
  "dvr": { code: "DVR", name: "Classic Battles: Rhinar vs Dorinthea", releaseDate: "2022-05-27", hasFirstEdition: false, category: "non-standard", tier: 2, displayOrder: 210 },
  "rvd": { code: "RVD", name: "Classic Battles: Rhinar vs Dorinthea - Rhinar", releaseDate: "2022-05-27", hasFirstEdition: false, category: "non-standard", tier: 2, displayOrder: 220 },
  "upr": { code: "UPR", name: "Uprising", releaseDate: "2022-06-24", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 70 },
  "dro": { code: "DRO", name: "Blitz Deck: Uprising - Dromai", releaseDate: "2022-06-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 530 },
  "fai": { code: "FAI", name: "Blitz Deck: Uprising - Fai", releaseDate: "2022-06-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 540 },
  "dyn": { code: "DYN", name: "Dynasty", releaseDate: "2022-11-11", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 80 },
  "1hb": { code: "1HB", name: "Historic Pack 1 Blitz Deck: Bravo", releaseDate: "2023-02-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 550 },
  "1hd": { code: "1HD", name: "Historic Pack 1 Blitz Deck: Dash", releaseDate: "2023-02-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 560 },
  "1hk": { code: "1HK", name: "Historic Pack 1 Blitz Deck: Kano", releaseDate: "2023-02-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 570 },
  "1hr": { code: "1HR", name: "Historic Pack 1 Blitz Deck: Rhinar", releaseDate: "2023-02-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 580 },
  "1ht": { code: "1HT", name: "Historic Pack 1 Blitz Deck: Dorinthea", releaseDate: "2023-02-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 590 },
  "1hv": { code: "1HV", name: "Historic Pack 1 Blitz Deck: Viserai", releaseDate: "2023-02-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 600 },
  "out": { code: "OUT", name: "Outsiders", releaseDate: "2023-03-24", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 90 },
  "ara": { code: "ARA", name: "Blitz Deck: Outsiders - Arakni", releaseDate: "2023-03-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 610 },
  "azl": { code: "AZL", name: "Blitz Deck: Outsiders - Azalea", releaseDate: "2023-03-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 620 },
  "ben": { code: "BEN", name: "Blitz Deck: Outsiders - Benji", releaseDate: "2023-03-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 630 },
  "kat": { code: "KAT", name: "Blitz Deck: Outsiders - Katsu", releaseDate: "2023-03-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 640 },
  "rip": { code: "RIP", name: "Blitz Deck: Outsiders - Riptide", releaseDate: "2023-03-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 650 },
  "uzu": { code: "UZU", name: "Blitz Deck: Outsiders - Uzuri", releaseDate: "2023-03-24", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 660 },
  "dtd": { code: "DTD", name: "Dusk till Dawn", releaseDate: "2023-07-23", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 100 },
  "tcc": { code: "TCC", name: "Round the Table: TCCxLSS", releaseDate: "2023-09-29", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 350 },
  "evo": { code: "EVO", name: "Bright Lights", releaseDate: "2023-10-06", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 110 },
  "gem": { code: "GEM", name: "GEM Pack 2", releaseDate: "2024-01-01", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 360 },
  "oxo": { code: "OXO", name: "Slingshot Underground Promos", releaseDate: "2024-01-01", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 370 },
  "hvy": { code: "HVY", name: "Heavy Hitters", releaseDate: "2024-02-02", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 120 },
  "bet": { code: "BET", name: "Blitz Deck: Heavy Hitters - Betsy", releaseDate: "2024-02-02", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 670 },
  "ksi": { code: "KSI", name: "Blitz Deck: Heavy Hitters - Kassai", releaseDate: "2024-02-02", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 680 },
  "kyo": { code: "KYO", name: "Blitz Deck: Heavy Hitters - Kayo", releaseDate: "2024-02-02", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 690 },
  "ola": { code: "OLA", name: "Blitz Deck: Heavy Hitters - Olympia", releaseDate: "2024-02-02", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 700 },
  "rhi": { code: "RHI", name: "Blitz Deck: Heavy Hitters - Rhinar", releaseDate: "2024-02-02", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 710 },
  "vic": { code: "VIC", name: "Blitz Deck: Heavy Hitters - Victor", releaseDate: "2024-02-02", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 720 },
  "ako": { code: "AKO", name: "Armory Deck: Kayo", releaseDate: "2024-05-03", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 960 },
  "mst": { code: "MST", name: "Part the Mistveil", releaseDate: "2024-05-31", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 130 },
  "eng": { code: "ENG", name: "Blitz Deck: Part the Mistveil - Enigma", releaseDate: "2024-05-31", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 730 },
  "nuu": { code: "NUU", name: "Blitz Deck: Part the Mistveil - Nuu", releaseDate: "2024-05-31", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 740 },
  "zen": { code: "ZEN", name: "Blitz Deck: Part the Mistveil - Zen", releaseDate: "2024-05-31", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 750 },
  "asb": { code: "ASB", name: "Armory Deck: Boltyn", releaseDate: "2024-07-12", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 970 },
  "aaz": { code: "AAZ", name: "Armory Deck: Azalea", releaseDate: "2024-08-02", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 980 },
  "aur": { code: "AUR", name: "1st Strike", releaseDate: "2024-08-23", hasFirstEdition: false, category: "non-standard", tier: 2, displayOrder: 230 },
  "ter": { code: "TER", name: "First Strike: Terra", releaseDate: "2024-08-23", hasFirstEdition: false, category: "non-standard", tier: 2, displayOrder: 240 },
  "ros": { code: "ROS", name: "Rosetta", releaseDate: "2024-09-20", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 140 },
  "aua": { code: "AUA", name: "Blitz Deck: Rosetta - Aurora", releaseDate: "2024-09-20", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 760 },
  "flr": { code: "FLR", name: "Blitz Deck: Rosetta - Florian", releaseDate: "2024-09-20", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 770 },
  "osc": { code: "OSC", name: "Blitz Deck: Rosetta - Oscilio", releaseDate: "2024-09-20", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 780 },
  "ver": { code: "VER", name: "Blitz Deck: Rosetta - Verdance", releaseDate: "2024-09-20", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 790 },
  "aio": { code: "AIO", name: "Armory Deck: Dash", releaseDate: "2024-10-18", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 990 },
  "ajv": { code: "AJV", name: "Armory Deck: Jarl Vetreidi", releaseDate: "2024-11-29", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1000 },
  "hnt": { code: "HNT", name: "The Hunted", releaseDate: "2025-01-31", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 150, defaultRarity: "L" },
  "ark": { code: "ARK", name: "Blitz Deck: The Hunted - Arakni", releaseDate: "2025-01-31", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 800 },
  "cin": { code: "CIN", name: "Blitz Deck: The Hunted - Cindra", releaseDate: "2025-01-31", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 810 },
  "fng": { code: "FNG", name: "Blitz Deck: The Hunted - Fang", releaseDate: "2025-01-31", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 820 },
  "wod": { code: "WOD", name: "Blitz Deck: The Hunted - Arakni, Web of Deceit", releaseDate: "2025-01-31", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 830 },
  "ast": { code: "AST", name: "Armory Deck: Aurora", releaseDate: "2025-03-14", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1010 },
  "amx": { code: "AMX", name: "Armory Deck: Maxx Nitro", releaseDate: "2025-04-17", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1020 },
  "agb": { code: "AGB", name: "Armory Deck: Gravy Bones", releaseDate: "2025-05-30", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1030 },
  "sea": { code: "SEA", name: "High Seas", releaseDate: "2025-06-06", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 160, defaultRarity: "L" },
  "asr": { code: "ASR", name: "Armory Deck: Ira", releaseDate: "2025-07-11", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1040 },
  "apr": { code: "APR", name: "Armory Deck Legends: Prism", releaseDate: "2025-07-24", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1050 },
  "avs": { code: "AVS", name: "Armory Deck Legends: Viserai", releaseDate: "2025-07-24", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1060 },
  "mpg": { code: "MPG", name: "Mastery Pack Guardian", releaseDate: "2025-08-08", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 170 },
  "bdd": { code: "BDD", name: "Bravo Demo Deck", releaseDate: "2025-08-08", hasFirstEdition: false, category: "excluded", tier: 3, displayOrder: 840 },
  "smp": { code: "SMP", name: "Smash Palace", releaseDate: "2025-08-29", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 380 },
  "aps": { code: "APS", name: "Armory Deck: Pleiades", releaseDate: "2025-09-19", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1070 },
  "sup": { code: "SUP", name: "Super Slam", releaseDate: "2025-09-26", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 180 },
  "arr": { code: "ARR", name: "Armory Deck: Rhinar", releaseDate: "2025-11-14", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1080 },
  "aac": { code: "AAC", name: "Armory Deck: Arakni", releaseDate: "2025-12-12", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1090 },
  "anq": { code: "ANQ", name: "Antiquity Pack", releaseDate: "2026-02-13", hasFirstEdition: false, category: "standard", tier: 2, displayOrder: 250 },
  "pen": { code: "PEN", name: "Compendium of Rathe", releaseDate: "2026-02-13", hasFirstEdition: false, category: "standard", tier: 2, displayOrder: 260 },
  "sar": { code: "SAR", name: "Silver Age Deck: Arakni", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 850 },
  "saz": { code: "SAZ", name: "Silver Age Deck: Azalea", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 860 },
  "sbr": { code: "SBR", name: "Silver Age Deck: Bravo", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 870 },
  "sda": { code: "SDA", name: "Silver Age Deck: Dash", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 880 },
  "sdo": { code: "SDO", name: "Silver Age Deck: Dorinthea", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 890 },
  "sen": { code: "SEN", name: "Silver Age Deck: Enigma", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 900 },
  "sfa": { code: "SFA", name: "Silver Age Deck: Fai", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 910 },
  "siy": { code: "SIY", name: "Silver Age Deck: Iyslander", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 920 },
  "ska": { code: "SKA", name: "Silver Age Deck: Kayo", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 930 },
  "svi": { code: "SVI", name: "Silver Age Deck: Viserai", releaseDate: "2026-02-13", hasFirstEdition: false, category: "non-standard", tier: 3, displayOrder: 940 },
  "aha": { code: "AHA", name: "Armory Deck Origins: Hala", releaseDate: "2026-04-17", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1100 },
  "azs": { code: "AZS", name: "Armory Deck: Zyggy", releaseDate: "2026-05-29", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1110 },
  "omn": { code: "OMN", name: "Omens of the Third Age", releaseDate: "2026-06-05", hasFirstEdition: false, category: "standard", tier: 1, displayOrder: 190 },
  "iar": { code: "IAR", name: "Íarathael Preview Cards", releaseDate: "2026-06-05", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 390 },
  "mpw": { code: "MPW", name: "Mastery Pack Warrior", releaseDate: "2026-07-08", hasFirstEdition: false, category: "non-standard", tier: 5, displayOrder: 400 },
  "ddd": { code: "DDD", name: "Dorinthea Demo Deck", releaseDate: "2026-08-07", hasFirstEdition: false, category: "excluded", tier: 3, displayOrder: 950 },
  "aol": { code: "AOL", name: "Armory Deck: Olympia", releaseDate: "2026-08-07", hasFirstEdition: false, category: "armory", tier: 4, displayOrder: 1120 },
};
