#!/usr/bin/env bash
# FaB Bazaar — Local Developer Setup
# Run once after cloning: bash dev-setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colours ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; RED='\033[0;31m'; NC='\033[0m'
header()  { echo -e "\n${BLUE}▶ $1${NC}"; }
success() { echo -e "  ${GREEN}✓${NC}  $1"; }
warn()    { echo -e "  ${YELLOW}⚠${NC}  $1"; }
fail()    { echo -e "  ${RED}✗${NC}  $1"; exit 1; }

echo ""
echo "================================================"
echo "  FaB Bazaar — Local Developer Setup"
echo "================================================"

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
header "Checking prerequisites"

command -v docker &>/dev/null  || fail "Docker not found. Install Docker Desktop: https://www.docker.com/products/docker-desktop"
docker info &>/dev/null        || fail "Docker is not running. Start Docker Desktop and re-run."
success "Docker $(docker --version | awk '{print $3}' | tr -d ',')"

command -v node &>/dev/null    || fail "Node.js not found. Install it at https://nodejs.org"
success "Node.js $(node --version)"

command -v npm &>/dev/null     || fail "npm not found."
success "npm $(npm --version)"

command -v openssl &>/dev/null || fail "openssl not found (needed to generate secrets)."

# ── 2. .env.local ─────────────────────────────────────────────────────────────
header "Environment configuration"

SKIP_ENV=false
if [ -f "${SCRIPT_DIR}/.env.local" ]; then
  warn ".env.local already exists."
  read -r -p "  Overwrite it? [y/N] " overwrite
  [[ "$overwrite" =~ ^[Yy]$ ]] || SKIP_ENV=true
fi

if [ "$SKIP_ENV" = false ]; then
  # Auto-generate secrets
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '=/+' | head -c 32)
  REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d '=/+' | head -c 32)
  NEXTAUTH_SECRET=$(openssl rand -base64 32)
  JWT_SECRET=$(openssl rand -base64 32)
  CRON_SECRET=$(openssl rand -base64 32)
  REVALIDATE_SECRET=$(openssl rand -base64 32)
  HASH_SALT=$(openssl rand -base64 16 | tr -d '=/+' | head -c 16)

  # Discord OAuth
  echo ""
  echo "  Discord OAuth is required for login. You need your own Discord application."
  echo ""
  echo "  Steps:"
  echo "    1. Go to https://discord.com/developers/applications"
  echo "    2. Click 'New Application' → name it anything (e.g. FabBazaar Dev)"
  echo "    3. General Information tab"
  echo "       - Copy the Public Key"
  echo "    4. OAuth2 tab"
  echo "       - Copy the Client ID"
  echo "       - Click 'Reset Secret' to generate and copy the Client Secret"
  echo "       - Under Redirects, click Add Redirect and enter:"
  echo "           http://localhost:3000/api/auth/callback/discord"
  echo "       - Set Default Authorization Link scopes to: identify, email"
  echo "    5. Bot tab (optional — only needed for bot/admin features)"
  echo "       - If you need a bot token, click 'Reset Token' to generate one"
  echo "       - Enable these Privileged Gateway Intents: Server Members, Message Content"
  echo ""
  echo "  Press Enter to skip any field for now (login won't work until they're filled in)."
  echo ""
  read -r -p "  Discord Client ID:     " DISCORD_CLIENT_ID
  read -r -p "  Discord Client Secret: " DISCORD_CLIENT_SECRET
  read -r -p "  Discord Public Key:    " DISCORD_PUBLIC_KEY

  cat > "${SCRIPT_DIR}/.env.local" << ENV
# FaB Bazaar — Local Development
# Generated by dev-setup.sh on $(date)
# NEVER commit this file.

# Database — PostgreSQL
# Note: uses the 'fabbazaar' superuser locally (fabbazaar_app is production-only)
POSTGRES_URL=postgresql://fabbazaar:${POSTGRES_PASSWORD}@localhost:5432/fabbazaar
POSTGRES_USER=fabbazaar
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=fabbazaar

# Database — Redis
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# Auth
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://localhost:3000
AUTH_URL=http://localhost:3000
JWT_SECRET=${JWT_SECRET}
CRON_SECRET=${CRON_SECRET}
REVALIDATE_SECRET_TOKEN=${REVALIDATE_SECRET}
# 64-char hex key for encrypting addresses — zeroes are fine for local dev
ADDRESS_ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000

# Discord OAuth — https://discord.com/developers/applications
DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
DISCORD_BOT_TOKEN=
DISCORD_VALIDATE_TOKEN_WITH_API=false

# Public (browser-exposed)
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_API_BASE_URL=http://localhost:3000
NEXT_PUBLIC_CLIENT_HASH_SALT=${HASH_SALT}
NEXT_PUBLIC_GA_ID=

# Feature flags
DATABASE_PROVIDER=postgres
ENABLE_FORUMS=false

# Internal
APP_VERSION=latest
MCP_API_BASE_URL=http://localhost:3000
ENV

  success "Created .env.local (secrets auto-generated)"

  if [ -z "${DISCORD_CLIENT_ID}" ]; then
    warn "Discord credentials not set — you can add them to .env.local later."
  fi
fi

# ── 3. npm install ────────────────────────────────────────────────────────────
header "Installing npm dependencies"
npm install --silent
success "Dependencies installed"

# ── 4. Docker services ────────────────────────────────────────────────────────
header "Starting Docker services"
docker compose up -d postgres redis
success "postgres and redis containers started"

echo "  Waiting for postgres to be ready..."
until docker exec fabbazaar-postgres pg_isready -U fabbazaar -d fabbazaar -q 2>/dev/null; do
  sleep 1
done
success "postgres is ready"

# ── 5. Migrations + seed ──────────────────────────────────────────────────────
header "Running database migrations and importing card data"
bash "${SCRIPT_DIR}/scripts/import-seed-data.sh"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "================================================"
echo "  All done! Start the app with:"
echo ""
echo "    npm run dev"
echo ""
echo "  Then open http://localhost:3000"
if [ -z "${DISCORD_CLIENT_ID:-}" ]; then
  echo ""
  warn "Discord credentials not set — add them to .env.local to enable login."
fi
echo "================================================"
echo ""
