-- 0124: tcg_group_sets — which TCGplayer (tcgcsv) groups price which set
--
-- The mapping lived only in pipeline/scripts/fab_set_with_db.csv, baked into
-- the pipeline image, so pointing a new set at its tcgcsv group took a code
-- change + deploy. Sets registered from /admin/cardvault store their groups
-- here; pipeline steps 001/002/009 read CSV + this table merged
-- (pipeline/scripts/group_mappings.py; the CSV stays the floor if the DB is
-- unreachable). Many-to-many: one group can hold several set codes (Silver
-- Age chapters), one set can use several groups (IAR's Marvels sit in the OMN
-- group). set_code has no FK on purpose — price-only codes such as
-- 'iar-prerelease' are not sets. Seeded with the CSV as of this migration.
-- Idempotent.

CREATE TABLE IF NOT EXISTS tcg_group_sets (
  group_id   INTEGER NOT NULL,
  set_code   TEXT NOT NULL,
  set_name   TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, set_code)
);

CREATE INDEX IF NOT EXISTS idx_tcg_group_sets_set_code ON tcg_group_sets (set_code);

INSERT INTO tcg_group_sets (group_id, set_code, set_name) VALUES
  (2724, 'cru', 'Crucible of War'),
  (2725, 'arc', 'Arcane Rising'),
  (2726, 'wtr', 'Welcome to Rathe'),
  (2727, 'ira', 'Welcome Deck: Ira'),
  (2728, 'bvo', 'Hero Deck: Bravo'),
  (2729, 'rnr', 'Hero Deck: Rhinar'),
  (2730, 'ksu', 'Hero Deck: Katsu'),
  (2731, 'tea', 'Hero Deck: Dorinthea'),
  (2732, 'fab', 'Flesh and Blood: Promo Cards'),
  (2775, 'mon', 'Monarch'),
  (2818, 'psm', 'Blitz Deck: Monarch - Prism'),
  (2819, 'bol', 'Blitz Deck: Monarch - Boltyn'),
  (2820, 'chn', 'Blitz Deck: Monarch - Chane'),
  (2821, 'lev', 'Blitz Deck: Monarch - Levia'),
  (2885, 'ele', 'Tales of Aria'),
  (2947, 'evr', 'Everfest'),
  (3016, 'lxi', 'Blitz Deck: Tales of Aria - Lexi'),
  (3017, 'old', 'Blitz Deck: Tales of Aria - Oldhim'),
  (3018, 'bri', 'Blitz Deck: Tales of Aria - Briar'),
  (3053, '1hp', 'History Pack Vol.1'),
  (3056, 'upr', 'Uprising'),
  (3057, 'dvr', 'Classic Battles: Rhinar vs Dorinthea'),
  (3059, 'fai', 'Blitz Deck: Uprising - Fai'),
  (3060, 'dro', 'Blitz Deck: Uprising - Dromai'),
  (17678, 'dyn', 'Dynasty'),
  (22893, 'out', 'Outsiders'),
  (22898, 'ara', 'Blitz Deck: Outsiders - Arakni'),
  (22899, 'azl', 'Blitz Deck: Outsiders - Azalea'),
  (22900, 'ben', 'Blitz Deck: Outsiders - Benji'),
  (22901, 'kat', 'Blitz Deck: Outsiders - Katsu'),
  (22902, 'rip', 'Blitz Deck: Outsiders - Riptide'),
  (22903, 'uzu', 'Blitz Deck: Outsiders - Uzuri'),
  (23173, 'dtd', 'Dusk till Dawn'),
  (23277, 'evo', 'Bright Lights'),
  (23295, 'tcc', 'Round the Table: TCCxLSS'),
  (23354, 'hvy', 'Heavy Hitters'),
  (23384, 'ksi', 'Blitz Deck: Heavy Hitters - Kassai'),
  (23388, 'kyo', 'Blitz Deck: Heavy Hitters - Kayo'),
  (23389, 'rhi', 'Blitz Deck: Heavy Hitters - Rhinar'),
  (23390, 'bet', 'Blitz Deck: Heavy Hitters - Betsy'),
  (23391, 'ola', 'Blitz Deck: Heavy Hitters - Olympia'),
  (23392, 'vic', 'Blitz Deck: Heavy Hitters - Victor'),
  (23476, 'mst', 'Part the Mistveil'),
  (23477, 'eng', 'Blitz Deck: Part the Mistveil - Enigma'),
  (23478, 'nuu', 'Blitz Deck: Part the Mistveil - Nuu'),
  (23479, 'zen', 'Blitz Deck: Part the Mistveil - Zen'),
  (23506, 'ako', 'Armory Deck: Kayo'),
  (23534, 'asb', 'Armory Deck: Boltyn'),
  (23540, 'ros', 'Rosetta'),
  (23548, 'aur', '1st Strike'),
  (23558, 'aaz', 'Armory Deck: Azalea'),
  (23738, 'aio', 'Armory Deck: Dash'),
  (23741, 'flr', 'Blitz Deck: Rosetta - Florian'),
  (23742, 'aua', 'Blitz Deck: Rosetta - Aurora'),
  (23744, 'osc', 'Blitz Deck: Rosetta - Oscilio'),
  (23745, 'ver', 'Blitz Deck: Rosetta - Verdance'),
  (23760, '1hb', 'Historic Pack 1 Blitz Deck: Bravo'),
  (23761, '1hd', 'Historic Pack 1 Blitz Deck: Dash'),
  (23762, '1ht', 'Historic Pack 1 Blitz Deck: Dorinthea'),
  (23763, '1hk', 'Historic Pack 1 Blitz Deck: Kano'),
  (23764, '1hr', 'Historic Pack 1 Blitz Deck: Rhinar'),
  (23765, '1hv', 'Historic Pack 1 Blitz Deck: Viserai'),
  (23771, 'ajv', 'Armory Deck: Jarl Vetreidi'),
  (23815, 'hnt', 'The Hunted'),
  (24162, 'ast', 'Armory Deck: Aurora'),
  (24176, 'gem', 'GEM Pack 1'),
  (24212, 'ark', 'Blitz Deck: The Hunted - Arakni'),
  (24213, 'fng', 'Blitz Deck: The Hunted - Fang'),
  (24214, 'wod', 'Blitz Deck: The Hunted - Arakni, Web of Deceit'),
  (24215, 'cin', 'Blitz Deck: The Hunted - Cindra'),
  (24253, 'amx', 'Armory Deck: Maxx Nitro'),
  (24266, 'sea', 'High Seas'),
  (24268, 'agb', 'Armory Deck: Gravy Bones'),
  (24315, 'asr', 'Armory Deck: Ira'),
  (24330, 'mpg', 'Mastery Pack Guardian'),
  (24334, 'gem', 'GEM Pack 2'),
  (24371, 'sup', 'Super Slam'),
  (24375, 'aps', 'Armory Deck: Pleiades'),
  (24391, 'bdd', 'Welcome Deck Bravo'),
  (24415, 'smp', 'Smash Palace'),
  (24416, 'avs', 'Armory Deck: Legends Viserai'),
  (24417, 'apr', 'Armory Deck: Legends Prism'),
  (24446, 'gem', 'GEM Pack 3'),
  (24474, 'arr', 'Armory Deck: Rhinar'),
  (24526, 'aac', 'Armory Deck: Arakni'),
  (24532, 'pen', 'Compendium of Rathe'),
  (24533, 'anq', 'Compendium of Rathe - Antiquity Pack'),
  (24610, 'aha', 'Armory Deck Origins: Hala'),
  (24620, 'gem', 'GEM Pack 4'),
  (24720, 'gem', 'GEM Pack 5'),
  (24524, 'sbr', 'Silver Age Chapter 1 - Bravo'),
  (24524, 'sda', 'Silver Age Chapter 1 - Dash'),
  (24524, 'siy', 'Silver Age Chapter 1 - Iyslander'),
  (24524, 'ska', 'Silver Age Chapter 1 - Kayo'),
  (24524, 'svi', 'Silver Age Chapter 1 - Viserai'),
  (24525, 'sar', 'Silver Age Chapter 2 - Arakni Web of Deceit'),
  (24525, 'saz', 'Silver Age Chapter 2 - Azalea'),
  (24525, 'sdo', 'Silver Age Chapter 2 - Dorinthea'),
  (24525, 'sen', 'Silver Age Chapter 2 - Enigma'),
  (24525, 'sfa', 'Silver Age Chapter 2 - Fai'),
  (24639, 'azs', 'Armory Deck - Zyggy'),
  (24640, 'omn', 'Omens of the Third Age'),
  (3057, 'rvd', 'Classic Battles: Rhinar vs Dorinthea - Rhinar'),
  (23548, 'ter', 'First Strike - Terra'),
  (24671, 'mpw', 'Mastery Pack Warrior'),
  (24672, 'aol', 'Armory Deck: Olympia'),
  (24706, 'sba', 'Silver Age Chapter 3 - Briar'),
  (24706, 'sbl', 'Silver Age Chapter 3 - Boltyn'),
  (24706, 'sbz', 'Silver Age Chapter 3 - Blaze Firemind'),
  (24706, 'sgb', 'Silver Age Chapter 3 - Gravy Bones'),
  (24706, 'sly', 'Silver Age Chapter 3 - Lyath Goldmane'),
  (24762, 'iar', 'Usurp the Shadow Throne'),
  (24640, 'iar', 'Omens of the Third Age'),
  (24776, 'iar-prerelease', 'Usurp the Shadow Throne Pre-release Cards'),
  (24763, 'ama', 'Armory Deck: Malice'),
  (24764, 'sat', 'Silver Age Chapter 4 - Prism'),
  (24764, 'sbw', 'Silver Age Chapter 4 - Viserai'),
  (24773, 'spw', 'Smash Palace: Chorus of Steel'),
  (24774, 'gem', 'GEM Pack 6'),
  (24814, 'amo', 'Armory Deck: Dr. Mortimer'),
  (24818, 'mpa', 'Mastery Pack Assassin')
ON CONFLICT (group_id, set_code) DO NOTHING;
