#!/bin/bash

################################################################################
# Daily Automated Pipeline for FAB Card Data Processing
#
# Pipeline order:
#   01 → 02 → 03 → 03B (images) → 04 → 08 (PG, price diff vs old DB) → 05 (PG, full upsert) → 11 (analysis) → 12 (discord)
#
# Database: PostgreSQL (local Docker staging by default)
#   Staging    = POSTGRES_URL_STAGING  (local Docker, fabbazaar_dev)
#   Production = POSTGRES_URL_PROD     (set when production DB is deployed)
#
# Usage:
#   ./daily_pipeline.sh              # Run against staging (safe default)
#   ./daily_pipeline.sh --staging    # Explicit staging
#   ./daily_pipeline.sh --production # Run against production (requires explicit flag)
#   ./daily_pipeline.sh --dry-run    # Test without any DB writes
#   ./daily_pipeline.sh --help       # Show this help
################################################################################

set -e          # Exit on error
set -u          # Exit on undefined variable
set -o pipefail # Pipe returns exit code of first failing command

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${SCRIPT_DIR}/logs"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FILE="${LOG_DIR}/pipeline_${TIMESTAMP}.log"

# File paths (generated by pipeline)
CARDS_ENHANCED="cards.enhanced.json"
CARDS_WITH_PRICES="cards_with_prices.json"
PRINTINGS_SEED="printings_collection_seed.json"
PRICE_SNAPSHOT="price_snapshot.json"

# Flags
DRY_RUN=false
STOP_ON_ERROR=true
USE_PRODUCTION=false
SKIP_DISCORD=false
DB_FLAG=""  # Set to --production when needed

# Create logs directory if it doesn't exist
mkdir -p "${LOG_DIR}"

################################################################################
# Helper Functions
################################################################################

log() {
    echo -e "${CYAN}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "${LOG_FILE}"
}

log_success() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] ✓ $1${NC}" | tee -a "${LOG_FILE}"
}

log_error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ✗ $1${NC}" | tee -a "${LOG_FILE}"
}

log_step() {
    echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "${LOG_FILE}"
    echo -e "${YELLOW}[STEP $1]${NC} $2" | tee -a "${LOG_FILE}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "${LOG_FILE}"
}

run_script() {
    local step_num=$1
    local description=$2
    local command=$3

    log_step "${step_num}" "${description}"
    log "Command: ${command}"

    local step_log="${LOG_DIR}/step_${step_num}_${TIMESTAMP}.log"

    if eval "${command}" 2>&1 | tee "${step_log}" | tee -a "${LOG_FILE}"; then
        log_success "Step ${step_num} completed successfully"
        return 0
    else
        log_error "Step ${step_num} failed"
        if [ "${STOP_ON_ERROR}" = true ]; then
            log_error "Pipeline stopped due to error. Check log: ${step_log}"
            exit 1
        fi
        return 1
    fi
}

show_help() {
    cat << EOF
Daily Automated Pipeline for FAB Card Data Processing

Usage: $0 [OPTIONS]

Options:
    --staging           Use STAGING database (DEFAULT - safest option)
    --production        Use PRODUCTION database (requires explicit flag)
    --dry-run           Run scripts in dry-run mode where applicable (no DB writes)
    --continue-on-error Don't stop pipeline if a step fails
    --skip-discord      Skip the Discord market poster step (step 12)
    --help              Show this help message

Database Selection:
    By default, the pipeline uses STAGING (local Docker: POSTGRES_URL_STAGING).
    Use --production flag to target production (POSTGRES_URL_PROD).

Pipeline Steps:
    01. API-Only Enhancer       - Download and enhance cards from GitHub API
    02. TCG Price Enhancer      - Add price data from TCGPlayer API
    03. Cards to Printings      - Transform cards into individual printings
    04. Price Snapshot Creator  - Create lean price snapshot + save to price_history/
    05. Weekly Printings Updater - Upsert all cards + printings into PostgreSQL
    08. Daily Price Updater     - Update all price fields in PostgreSQL printings table
    11. Price Analysis Export   - Compare two price_history snapshots, generate market analysis
    12. Discord Market Poster   - Post market analysis to Discord

Required environment variables:
    POSTGRES_URL_STAGING  (e.g. postgresql://fab_pipeline:pass@localhost:5432/fabbazaar_dev)
    POSTGRES_URL_PROD     (set when production DB is deployed)

Logs:
    Main log:  logs/pipeline_TIMESTAMP.log
    Step logs: logs/step_N_TIMESTAMP.log

Examples:
    $0 --dry-run        # Test without any DB writes (recommended first run)
    $0 --staging        # Run against local Docker staging DB
    $0 --production     # Run against production DB (explicit flag required)

EOF
}

################################################################################
# Parse Arguments
################################################################################

while [[ $# -gt 0 ]]; do
    case $1 in
        --staging)
            USE_PRODUCTION=false
            shift
            ;;
        --production)
            USE_PRODUCTION=true
            DB_FLAG="--production"
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --continue-on-error)
            STOP_ON_ERROR=false
            shift
            ;;
        --skip-discord)
            SKIP_DISCORD=true
            shift
            ;;
        --help)
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

################################################################################
# Pipeline Start
################################################################################

log "════════════════════════════════════════════════════════════════"
log "   Daily FAB Card Data Pipeline"
log "════════════════════════════════════════════════════════════════"
log "Start time: $(date)"
log "Working directory: ${SCRIPT_DIR}"
log "Log file: ${LOG_FILE}"

# Display database target prominently
if [ "${USE_PRODUCTION}" = true ]; then
    echo -e "\n${RED}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}║  ⚠️  WARNING: TARGETING PRODUCTION DATABASE  ⚠️           ║${NC}"
    echo -e "${RED}╚════════════════════════════════════════════════════════════╝${NC}\n"
    log "🎯 Database target: PRODUCTION (PostgreSQL)"
else
    echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  🧪 SAFE MODE: Using STAGING Database (local Docker)      ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}\n"
    log "🧪 Database target: STAGING (PostgreSQL, safe mode)"
fi

if [ "${DRY_RUN}" = true ]; then
    log "🔍 DRY RUN MODE ENABLED - No database changes will be made"
fi

PIPELINE_START=$(date +%s)

################################################################################
# Step 01: API-Only Enhancer
################################################################################

run_script "01" "API-Only Enhancer - Download and enhance cards from GitHub" \
    "python3 001_api_only_enhancer.py --output ${CARDS_ENHANCED}"

################################################################################
# Step 02: TCG Price Enhancer
################################################################################

run_script "02" "TCG Price Enhancer - Add price data from TCGPlayer API" \
    "python3 002_tcg_price_enhancer.py ${CARDS_ENHANCED} --output ${CARDS_WITH_PRICES}"

################################################################################
# Step 03: Cards to Printings Transformer
################################################################################

run_script "03" "Cards to Printings Transformer - Transform to individual printings" \
    "python3 003_cards_to_printings_transformer.py ${CARDS_WITH_PRICES} --output ${PRINTINGS_SEED}"

################################################################################
# Step 03B: Image Uploader - Download & upload images for new printings
################################################################################

if [ "${DRY_RUN}" = true ]; then
    run_script "03B" "Image Uploader - Download and upload images for new printings (DRY RUN)" \
        "python3 003b_image_uploader.py ${PRINTINGS_SEED} --dry-run ${DB_FLAG}"
else
    run_script "03B" "Image Uploader - Download and upload images for new printings" \
        "python3 003b_image_uploader.py ${PRINTINGS_SEED} ${DB_FLAG}"
fi

################################################################################
# Step 04: Price Snapshot Creator
################################################################################

if [ "${DRY_RUN}" = true ]; then
    run_script "04" "Price Snapshot Creator - Create lean price snapshot (DRY RUN)" \
        "python3 004_price_snapshot_creator.py ${PRINTINGS_SEED} --output ${PRICE_SNAPSHOT} --dry-run"
else
    run_script "04" "Price Snapshot Creator - Create lean price snapshot + history backup" \
        "python3 004_price_snapshot_creator.py ${PRINTINGS_SEED} --output ${PRICE_SNAPSHOT}"
fi

################################################################################
# Step 08: Daily Price Updater → PostgreSQL (compare new snapshot vs old DB prices)
# Runs BEFORE Step 05 so it sees yesterday's prices still in the DB
################################################################################

if [ "${DRY_RUN}" = true ]; then
    run_script "08" "Daily Price Updater - Update all price fields in PostgreSQL (DRY RUN)" \
        "python3 006_daily_price_updater.py ${PRICE_SNAPSHOT} --dry-run ${DB_FLAG}"
else
    run_script "08" "Daily Price Updater - Update all price fields in PostgreSQL" \
        "python3 006_daily_price_updater.py ${PRICE_SNAPSHOT} --auto-confirm ${DB_FLAG}"
fi

################################################################################
# Step 05: Weekly Printings Updater → PostgreSQL (cards + printings upsert)
################################################################################

if [ "${DRY_RUN}" = true ]; then
    run_script "05" "Weekly Printings Updater - Upsert cards + printings to PostgreSQL (DRY RUN)" \
        "python3 005_weekly_printings_updater.py --file ${PRINTINGS_SEED} --dry-run ${DB_FLAG}"
else
    run_script "05" "Weekly Printings Updater - Upsert cards + printings to PostgreSQL" \
        "python3 005_weekly_printings_updater.py --file ${PRINTINGS_SEED} ${DB_FLAG}"
fi

################################################################################
# Step 11: Price Analysis Export
################################################################################

# Find the two most recent snapshots in price_history/ by Unix timestamp in filename
HISTORY_DIR="${SCRIPT_DIR}/price_history"
if [ -d "${HISTORY_DIR}" ]; then
    NEWEST_FILE=$(ls "${HISTORY_DIR}"/*.json 2>/dev/null | \
                  sed 's/.*_\([0-9]*\)\.json/\1 &/' | \
                  sort -rn | \
                  head -1 | \
                  cut -d' ' -f2)
    SECOND_NEWEST_FILE=$(ls "${HISTORY_DIR}"/*.json 2>/dev/null | \
                         sed 's/.*_\([0-9]*\)\.json/\1 &/' | \
                         sort -rn | \
                         head -2 | \
                         tail -1 | \
                         cut -d' ' -f2)

    if [ -n "${NEWEST_FILE}" ] && [ -n "${SECOND_NEWEST_FILE}" ] && [ "${NEWEST_FILE}" != "${SECOND_NEWEST_FILE}" ]; then
        run_script "11" "Price Analysis Export - Compare historical snapshots and generate market analysis" \
            "python3 007_price_analysis.py \"${SECOND_NEWEST_FILE}\" \"${NEWEST_FILE}\""
    else
        log "⚠️  Step 11 skipped - Need at least 2 snapshots in price_history/ for comparison"
    fi
else
    log "⚠️  Step 11 skipped - price_history/ directory not found"
fi

################################################################################
# Step 12: Discord Market Poster
################################################################################

if [ "${SKIP_DISCORD}" = true ]; then
    log "⏭️  Step 12 skipped (--skip-discord)"
else
    run_script "12" "Discord Market Poster - Post market analysis to Discord" \
        "python3 008_discord_market_poster.py"
fi

################################################################################
# Pipeline Complete
################################################################################

PIPELINE_END=$(date +%s)
PIPELINE_DURATION=$((PIPELINE_END - PIPELINE_START))
DURATION_MIN=$((PIPELINE_DURATION / 60))
DURATION_SEC=$((PIPELINE_DURATION % 60))

echo -e "\n${GREEN}════════════════════════════════════════════════════════════════${NC}" | tee -a "${LOG_FILE}"
echo -e "${GREEN}   Pipeline Completed Successfully!${NC}" | tee -a "${LOG_FILE}"
echo -e "${GREEN}════════════════════════════════════════════════════════════════${NC}" | tee -a "${LOG_FILE}"
log "End time: $(date)"
log "Total duration: ${DURATION_MIN}m ${DURATION_SEC}s"
log "Main log: ${LOG_FILE}"
log "Generated files:"
log "  - ${CARDS_ENHANCED}"
log "  - ${CARDS_WITH_PRICES}"
log "  - ${PRINTINGS_SEED}"
log "  - ${PRICE_SNAPSHOT}"

if [ "${DRY_RUN}" = true ]; then
    log "🔍 DRY RUN completed - No database changes were made"
fi

log "════════════════════════════════════════════════════════════════"
