/**
 * Fetches countries + states from dr5hn/countries-states-cities-database
 * and writes the seed SQL to lib/postgres/migrations/0013_seed_countries_states.sql
 *
 * Run: npx ts-node scripts/generate-geo-seed.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BASE_URL =
  'https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/refs/heads/master/json';

const OUTPUT_FILE = path.join(
  __dirname,
  '../lib/postgres/migrations/0013_seed_countries_states.sql'
);

function fetch(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => resolve(data));
      res.on('error', reject);
    }).on('error', reject);
  });
}

function escape(val: string | null | undefined): string {
  if (val === null || val === undefined) return 'NULL';
  return `'${String(val).replace(/'/g, "''")}'`;
}

async function main() {
  console.log('Fetching countries.json...');
  const countriesRaw = await fetch(`${BASE_URL}/countries.json`);
  const countries: any[] = JSON.parse(countriesRaw);

  console.log(`Got ${countries.length} countries`);

  console.log('Fetching states.json...');
  const statesRaw = await fetch(`${BASE_URL}/states.json`);
  const states: any[] = JSON.parse(statesRaw);

  console.log(`Got ${states.length} states/provinces`);

  // Build SQL
  const lines: string[] = [];

  lines.push(`-- Auto-generated by scripts/generate-geo-seed.ts`);
  lines.push(`-- Source: dr5hn/countries-states-cities-database`);
  lines.push(`-- Countries: ${countries.length}, States: ${states.length}`);
  lines.push(`-- Do not re-run on an already-populated database.\n`);

  // Countries
  lines.push(`-- ============================================================================`);
  lines.push(`-- COUNTRIES`);
  lines.push(`-- ============================================================================\n`);

  const countryChunks: string[] = [];
  for (const c of countries) {
    const phoneCode = c.phonecode ?? c.phone_code ?? null;
    countryChunks.push(
      `  (${c.id}, ${escape(c.name)}, ${escape(c.iso2)}, ${escape(c.iso3)}, ${escape(phoneCode)})`
    );
  }

  lines.push(`INSERT INTO countries (id, name, iso2, iso3, phone_code) VALUES`);
  lines.push(countryChunks.join(',\n') + ';');
  lines.push('');

  // States — only include rows where country_id matches a known country
  const countryIds = new Set(countries.map((c) => c.id));
  const validStates = states.filter((s) => countryIds.has(s.country_id));

  lines.push(`-- ============================================================================`);
  lines.push(`-- STATES / PROVINCES`);
  lines.push(`-- ============================================================================\n`);

  const stateChunks: string[] = [];
  for (const s of validStates) {
    const code = s.state_code ?? s.iso2 ?? null;
    stateChunks.push(
      `  (${s.id}, ${escape(s.name)}, ${escape(code)}, ${s.country_id})`
    );
  }

  lines.push(`INSERT INTO states (id, name, state_code, country_id) VALUES`);
  lines.push(stateChunks.join(',\n') + ';');
  lines.push('');

  const sql = lines.join('\n');
  fs.writeFileSync(OUTPUT_FILE, sql, 'utf8');

  console.log(`\nWrote ${OUTPUT_FILE}`);
  console.log(`  Countries: ${countries.length}`);
  console.log(`  States:    ${validStates.length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
